# Numpy

In [3]:
import numpy as np  #Import Numpy module and use short notation "np" to address structures and methods inside it

### Creation

In [30]:
l = [1,2,3]
arr = np.array(l) #From a list
arr

array([1, 2, 3])

In [8]:
arr = np.arange(5) #From a range
arr

array([0, 1, 2, 3, 4])

In [9]:
arr = np.array(range(5)) #Equivalent to the above
arr

array([0, 1, 2, 3, 4])

In [18]:
np.arange(2,9,2) #Array of even numbers between 2 and 9

array([2, 4, 6, 8])

In [12]:
np.zeros(5) #Array of 5 zeros

array([ 0.,  0.,  0.,  0.,  0.])

In [15]:
np.zeros((2,3)) #2D array of zeros

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
np.ones(3) #Array of 3 ones

array([ 1.,  1.,  1.])

In [17]:
np.ones((3,2)) #2D array of ones

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [39]:
np.linspace(0,2,9) #Array of 9 equidistant numbers between 0 and 2. !Useful for plotting!

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [21]:
np.eye(3) #Unity matrix 3x3

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [25]:
np.random.randint(2,size=5) #Random array of 5 integers between 0 and 2-1

array([0, 0, 0, 1, 1])

In [27]:
np.random.rand(3) #Random arrays of 3 floats between 0 and 1

array([ 0.50060468,  0.90546815,  0.59372061])

In [29]:
np.random.rand(2,3) #2D random array

array([[ 0.5107163 ,  0.33683373,  0.84254443],
       [ 0.51509848,  0.93675662,  0.54258558]])

### Reshape

In [31]:
arr = np.random.rand(2,3)
arr

array([[ 0.52049603,  0.4263519 ,  0.3688723 ],
       [ 0.58979243,  0.4742582 ,  0.25071141]])

In [33]:
arr.shape #Gives the number of rows and columns

(2, 3)

In [35]:
arr.size #Gives the total number of elements

6

In [37]:
len(arr) #Gives the number of rows

2

In [51]:
arr.ndim #Gives the number of dimensions

2

In [38]:
arr.reshape(3,2) #Change the chape of an array

array([[ 0.52049603,  0.4263519 ],
       [ 0.3688723 ,  0.58979243],
       [ 0.4742582 ,  0.25071141]])

In [40]:
arr #After reshape the initial array is not changed

array([[ 0.52049603,  0.4263519 ,  0.3688723 ],
       [ 0.58979243,  0.4742582 ,  0.25071141]])

In [42]:
arr.resize(3,2) #Resize change the shape of an array in place
arr

array([[ 0.52049603,  0.4263519 ],
       [ 0.3688723 ,  0.58979243],
       [ 0.4742582 ,  0.25071141]])

In [45]:
arr.ravel() #Flatten an array

array([ 0.52049603,  0.4263519 ,  0.3688723 ,  0.58979243,  0.4742582 ,
        0.25071141])

In [46]:
arr

array([[ 0.52049603,  0.4263519 ],
       [ 0.3688723 ,  0.58979243],
       [ 0.4742582 ,  0.25071141]])

In [47]:
arr.T #Transpose an array

array([[ 0.52049603,  0.3688723 ,  0.4742582 ],
       [ 0.4263519 ,  0.58979243,  0.25071141]])

### Indexing, slicing, iterating

In [56]:
arr = np.arange(2,9,2)
arr

array([2, 4, 6, 8])

In [58]:
arr[0] #Index starts with 0

2

In [59]:
arr[-1] #Last element has index -1

8

In [62]:
arr[:2] #All elements from index 0 up to index 2-1

array([2, 4])

In [63]:
arr[::2] #Each second element

array([2, 6])

In [64]:
arr[::-1] #Reverse array

array([8, 6, 4, 2])

In [65]:
arr = np.random.rand(2,3)
arr

array([[ 0.08049152,  0.23545192,  0.91082486],
       [ 0.78511434,  0.75516243,  0.7933955 ]])

In [67]:
arr[1] #Gives second row

array([ 0.78511434,  0.75516243,  0.7933955 ])

In [68]:
arr[:,1] #Gives second column

array([ 0.23545192,  0.75516243])

In [69]:
arr[:2,1:3] #Subarray

array([[ 0.23545192,  0.91082486],
       [ 0.75516243,  0.7933955 ]])

In [71]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [72]:
for x in arr: #Iterate over array
    print(x)

0
1
2
3
4


In [73]:
arr = np.arange(6).reshape(3,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [75]:
for row in arr:
    for x in row:
        print(x)

0
1
2
3
4
5


### Operations on a single array

In [76]:
arr = np.arange(6).reshape(3,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [79]:
np.sin(arr) #Operates on each element of an array

array([[ 0.        ,  0.84147098],
       [ 0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427]])

In [80]:
arr < 2 #Result = boolean array

array([[ True,  True],
       [False, False],
       [False, False]], dtype=bool)

In [82]:
arr*10 #Operates on each element

array([[ 0, 10],
       [20, 30],
       [40, 50]])

In [84]:
arr+=1 #Increment each element by 1
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
arr.min() #Minimum of an array

1

In [88]:
arr.sum() #Sum of all elements in an array

21

In [90]:
arr.mean() #Mean of all elements

3.5

In [94]:
arr.std() #Standard deviation of all elements in an array

1.707825127659933

In [95]:
arr.cumsum() #Cumulative sum of all previous elements in an array

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [96]:
np.exp(arr) #Exponent of each element

array([[   2.71828183,    7.3890561 ],
       [  20.08553692,   54.59815003],
       [ 148.4131591 ,  403.42879349]])

In [97]:
np.sqrt(arr) #Square root of each element

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ],
       [ 2.23606798,  2.44948974]])

In [101]:
np.sqrt(arr - 3) #np.nan is a "not defined value"

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


array([[        nan,         nan],
       [ 0.        ,  1.        ],
       [ 1.41421356,  1.73205081]])

In [104]:
np.nan == np.nan #Not defined values are not the same

False